GET http://localhost:5026/games

###
GET http://localhost:5026/games/1

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "Rumbleverse",
    "genreId": 1,
    "price": 9.00,
    "releaseDate": "2022-08-11"
}

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "The Last of Us I Remastered",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2024-06-05"
}

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "Bad Game",
    "genreId": 3,
    "price": 29.99,
    "releaseDate": "2026-04-17"
}

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "BadRequest",
    "genre": 1,
    "price": 199.00,
    "releaseDate": "2022-08-11"
}

###
PUT http://localhost:5026/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": 1,
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
PUT http://localhost:5026/games/2
Content-Type: application/json

{
    "name": "The Last of Us I Remastered",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2024-06-08"
}


###
DELETE http://localhost:5026/games/3

###
GET http://localhost:5026/genres