GET http://localhost:5026/games

###
GET http://localhost:5026/games/5

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "Rumbleverse",
    "genre": "Battle-Royale",
    "price": 0.00,
    "releaseDate": "2022-08-11"
}

###
POST http://localhost:5026/games
Content-Type: application/json

{
    "name": "BadRequest",
    "genre": "Battle-Royale",
    "price": 199.00,
    "releaseDate": "2022-08-11"
}

###
PUT http://localhost:5026/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
PUT http://localhost:5026/games/1
Content-Type: application/json

{
    "name": "BadPutRequest",
    "genre": "",
    "price": 999.99,
    "releaseDate": "1992-07-15"
}


###
DELETE http://localhost:5026/games/1